FROM golang:1.26.2-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o chat-server ./services/chat/cmd/server/main.go
 
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/chat-server .
COPY --from=builder /app/services/chat/migrations ./migrations
COPY --from=builder /app/services/chat/internal/api ./api
EXPOSE 8080
CMD ["./chat-server"]
 