FROM golang:1.26.2-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o analytics-server ./services/analytics/cmd/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/analytics-server .
COPY --from=builder /app/services/analytics/internal/api ./api
EXPOSE 8083
CMD ["./analytics-server"]